Update code_security.yml

diff --git a/.github/workflows/code_security.yml b/.github/workflows/code_security.yml
--- a/.github/workflows/code_security.yml
+++ b/.github/workflows/code_security.yml
@@ -132,14 +132,28 @@ jobs:
         with:
             #command : code test 
             args: --sarif-file-output=packages.sarif
+      - name: Count total number of vulnerabilities
+        run: |
+          RESULTS_LENGTH=$(jq '.runs[0].results | length' snyk.sarif)
+          echo "RESULTS_LENGTH=$RESULTS_LENGTH" >> $GITHUB_ENV
+          echo $RESULTS_LENGTH
+          
+      - name: Pass_or_Fail_the_job
+        run: |
+            if [ "$RESULTS_LENGTH" != 0 ]; then
+                echo "Job Failed"
+                exit 1
+            else
+                echo "Pass"
+            fi
+      
       - name: Send notification on Slack using Webhooks
         uses: slackapi/slack-github-action@v1.24.0
         if: always()
         with:
           payload: |
                {
-                 "title": "TEST TITLE"
-                 "text": "TEST"
+                 "text": "*The Snyk scan result for repo is : ${{ job.status }}* \n*Number of vulnerabilities : ${{ env.RESULTS_LENGTH }}* \n*Detail*: https://github.com/${{ github.repository }}/actions/runs/${{ github.run_id }}"
                }
         env:
           SLACK_WEBHOOK_URL: ${{ secrets.MSTEAMS_WEBHOOK_URL }}
